include: package:coca_lints/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    library_private_types_in_public_api: false
    avoid_print: false
    document_ignores: false
