name: coca_code
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.7.2

dev_dependencies:
  test: ^1.25.5
  coca_lints: ^1.0.0

dependencies:
  collection: ^1.19.0
