name: Dart CI

on:
    push:
        branches:
            - variables-homework
    pull_request:
        branches:
            - variables-homework

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Dart
              uses: dart-lang/setup-dart@v1
              with:
                sdk: stable

            - name: Install dependencies
              run: dart pub get

            - name: Run analyze
              run: dart analyze --fatal-infos --fatal-warnings

            - name: Run tests
              run: dart test
